const options = [
  'Morrisons',
  'Prime Video',
  'Free Delivery',
  'Buy Again',
  'Vouchers',
  'Gift Cards & Top Up',
  'Shopper Toolkit',
  'Health & Personal Care',
  'Home & Garden',
  "Today's Deals",
  'Prime',
  'Audible',
  'Books',
  'PC & Video Games',
  'Vouchers',
  'Fashion',
  'Gift Cards & Top Up',
  'Home & Garden',
  'Toys & Games',
  'Electronic',
  'PC',
  'Car & Motorbike',
  'Sports & Outdoors',
  'Pet Supplies',
  'Baby',
  'Kindle Books',
  'Shopper Toolkit',
  'Sell on Amazon',
  'Subscribe & Save',
  'Wish Lists',
  'Disability Customer Suppoort',
];

export default options;
